fig = figure('Units','pixels','Position',[0 0 1024 768],'PaperUnits','points',...
    'PaperPosition',[0 0 1024 768],'PaperSize', [1024 768]);
ax = axes(fig,'Position',[0 0 1 1]);

l = laserdata(fpaths{3},1);
l = l./imgaussfilt(l,64);
l = 3*normalise(l)-0.4;
lays = loaddata(fpaths{3},1,'manuallayers','int8');
height = heightdata(fpaths{3},1);
height = height - imgaussfilt(height,128)+0.3;
im = real2rgb(height,myxocmap,[0 0.5]);
imr = im(:,:,1);
img = im(:,:,2);
imb = im(:,:,3);
imr = imr.*l;
img = img.*l;
imb = imb.*l;
im(:,:,1) = imr;
im(:,:,2) = img;
im(:,:,3) = imb;
imshow(im)
axis off

colormap gray
caxis([0.7 1.3])

hold on
defs = load([fpaths{3} 'adefs.mat']);

defs = defs.adefs;
cdefs = defs([defs.ts]==1);
l = 15;
ncol = [0 0 255]/255;
pcol = [238 34 12]/255;
ncolrim = [0.5 0.9 1];
pcolrim = [1 0.9 0.5];
for i = 1:numel(cdefs)
    if cdefs(i).q>0
        plot(cdefs(i).x,cdefs(i).y,'.','MarkerSize',35,'Color',pcolrim)
        plot([cdefs(i).x cdefs(i).x+l*cdefs(i).d(1),...
            cdefs(i).x],...
            [cdefs(i).y cdefs(i).y+l*cdefs(i).d(2),...
            cdefs(i).y],'LineWidth',6,'Color',pcolrim);
        plot(cdefs(i).x,cdefs(i).y,'.','MarkerSize',30,'Color',pcol)
        plot([cdefs(i).x cdefs(i).x+l*cdefs(i).d(1),...
            cdefs(i).x],...
            [cdefs(i).y cdefs(i).y+l*cdefs(i).d(2),...
            cdefs(i).y],'LineWidth',4,'Color',pcol);
    else
        plot(cdefs(i).x,cdefs(i).y,'.','MarkerSize',35,'Color',ncolrim)
        theta = atan2(cdefs(i).d(2),cdefs(i).d(1));
        plot([cdefs(i).x cdefs(i).x+l*cos(theta) ...
            cdefs(i).x cdefs(i).x+l*cos(theta+2*pi/3) ...
            cdefs(i).x cdefs(i).x+l*cos(theta+4*pi/3),...
            cdefs(i).x],...
            [cdefs(i).y cdefs(i).y+l*sin(theta)...
            cdefs(i).y cdefs(i).y+l*sin(theta+2*pi/3)...
            cdefs(i).y cdefs(i).y+l*sin(theta+4*pi/3),...
            cdefs(i).y],...
            'Color',ncolrim,'LineWidth',6);

        plot(cdefs(i).x,cdefs(i).y,'.','MarkerSize',30,'Color',ncol)
        plot([cdefs(i).x cdefs(i).x+l*cos(theta) ...
            cdefs(i).x cdefs(i).x+l*cos(theta+2*pi/3) ...
            cdefs(i).x cdefs(i).x+l*cos(theta+4*pi/3),...
            cdefs(i).x],...
            [cdefs(i).y cdefs(i).y+l*sin(theta)...
            cdefs(i).y cdefs(i).y+l*sin(theta+2*pi/3)...
            cdefs(i).y cdefs(i).y+l*sin(theta+4*pi/3),...
            cdefs(i).y],...
            'Color',ncol,'LineWidth',4);
    end
end